# Generated by Django 3.1.7 on 2021-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=5)),
                ('Provincename', models.CharField(blank=True, choices=[('Zambia', 'Zambia'), ('Lusaka', 'Lusaka'), ('Copperbelt', 'Copperbelt'), ('Luapula', 'Luapula'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Northern', 'Northern'), ('Western', 'Western'), ('North-Western', 'North-Western'), ('Muchinga', 'Muchinga')], max_length=20)),
                ('provinceCode', models.CharField(blank=True, choices=[('ZM', 'ZM'), ('LS', 'LS'), ('CO', 'CO'), ('LP', 'LP'), ('CE', 'CE'), ('EA', 'EA'), ('SO', 'SO'), ('NO', 'NO'), ('WE', 'WE'), ('NW', 'NW'), ('MU', 'MU')], max_length=4)),
                ('candidate1vote', models.CharField(blank=True, max_length=30)),
                ('candidate2vote', models.CharField(blank=True, max_length=30)),
                ('provincewinner', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('candidate1', models.CharField(max_length=5)),
                ('candidate2', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sixteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=5)),
                ('Provincename', models.CharField(blank=True, choices=[('Zambia', 'Zambia'), ('Lusaka', 'Lusaka'), ('Copperbelt', 'Copperbelt'), ('Luapula', 'Luapula'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Northern', 'Northern'), ('Western', 'Western'), ('North-Western', 'North-Western'), ('Muchinga', 'Muchinga')], max_length=20)),
                ('provinceCode', models.CharField(blank=True, choices=[('ZM', 'ZM'), ('LS', 'LS'), ('CO', 'CO'), ('LP', 'LP'), ('CE', 'CE'), ('EA', 'EA'), ('SO', 'SO'), ('NO', 'NO'), ('WE', 'WE'), ('NW', 'NW'), ('MU', 'MU')], max_length=4)),
                ('candidate1vote', models.CharField(blank=True, max_length=30)),
                ('candidate2vote', models.CharField(blank=True, max_length=30)),
                ('provincewinner', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TwentyOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=5)),
                ('Provincename', models.CharField(blank=True, choices=[('Zambia', 'Zambia'), ('Lusaka', 'Lusaka'), ('Copperbelt', 'Copperbelt'), ('Luapula', 'Luapula'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Northern', 'Northern'), ('Western', 'Western'), ('North-Western', 'North-Western'), ('Muchinga', 'Muchinga')], max_length=20)),
                ('provinceCode', models.CharField(blank=True, choices=[('ZM', 'ZM'), ('LS', 'LS'), ('CO', 'CO'), ('LP', 'LP'), ('CE', 'CE'), ('EA', 'EA'), ('SO', 'SO'), ('NO', 'NO'), ('WE', 'WE'), ('NW', 'NW'), ('MU', 'MU')], max_length=4)),
                ('candidate1vote', models.CharField(blank=True, max_length=30)),
                ('candidate2vote', models.CharField(blank=True, max_length=30)),
                ('provincewinner', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=20)),
            ],
        ),
    ]
