# Generated by Django 3.1.7 on 2021-08-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zambiadecides21', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressbar',
            name='cadidate1votes',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='progressbar',
            name='cadidate2votes',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='eleven',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('0', '0')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sixteen',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('0', '0')], max_length=20),
        ),
        migrations.AlterField(
            model_name='twentyone',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('0', '0')], max_length=20),
        ),
    ]
