# Generated by Django 3.1.7 on 2021-08-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zambiadecides21', '0002_auto_20210808_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleven',
            name='reported',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sixteen',
            name='reported',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='twentyone',
            name='reported',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eleven',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('0', '0'), ('10', '10')], max_length=20),
        ),
        migrations.AlterField(
            model_name='progressbar',
            name='candidate1',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='progressbar',
            name='candidate2',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sixteen',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('0', '0'), ('10', '10')], max_length=20),
        ),
        migrations.AlterField(
            model_name='twentyone',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('0', '0'), ('10', '10')], max_length=20),
        ),
    ]
