# Generated by Django 3.1.7 on 2021-08-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zambiadecides21', '0003_auto_20210808_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('figure', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='eleven',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('1.5', '1.5'), ('2.5', '2.5'), ('4', '4'), ('0', '0')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sixteen',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('1.5', '1.5'), ('2.5', '2.5'), ('4', '4'), ('0', '0')], max_length=20),
        ),
        migrations.AlterField(
            model_name='twentyone',
            name='provincewinner',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('1.5', '1.5'), ('2.5', '2.5'), ('4', '4'), ('0', '0')], max_length=20),
        ),
    ]
