# Generated by Django 3.1.7 on 2021-08-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zambiadecides21', '0004_auto_20210809_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
